version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_non_tags: true

image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

before_build:
- ps: nuget restore

build:
  verbosity: minimal

test: off