version: 2.0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_non_tags: true

image: Visual Studio 2017
configuration: Release

nuget:
  disable_publish_on_pr: true

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

after_build:
- cmd: "7z a tumbler.zip %APPVEYOR_BUILD_FOLDER%\\Tumbler\\bin\\Release\\net461\\Tumbler.exe \n7z a tumbler.zip %APPVEYOR_BUILD_FOLDER%\\Tumbler\\bin\\Release\\net461\\tumblerfile.xml"

test: off

artifacts:
- path: tumbler.zip
  name: app_archive

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  auth_token:
    secure: xcRlHNsFt4uvxrweMuH4c1cozx0B2jxT0/UDxJFKYFAqgBWVtVV7D5A7P9aNH1pJ
  artifact: tumbler.zip