version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_non_tags: true

image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

before_build:
- ps: nuget restore

build:
  verbosity: minimal

test: off

artifacts:
- path: /.*\.exe/

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  auth_token:
    secure: xcRlHNsFt4uvxrweMuH4c1cozx0B2jxT0/UDxJFKYFAqgBWVtVV7D5A7P9aNH1pJ
  artifact: /.*\.exe/